version: '3.9'

services:

  enderecos:
    image: enderecos_endereco:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    ports:
      - 16000:80
    networks:
      - traefik-public
    deploy:

      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"

        - "traefik.http.routers.enderecos_egresso.rule=Host(`egressos.computacao.ufpa.br`) && PathPrefix(`/enderecos`)"
        - "traefik.http.routers.enderecos_egresso.entrypoints=http"
        - "traefik.http.routers.enderecos_egresso.middlewares=https-redirect@file,enderecos_egresso-strip@docker"

        - "traefik.http.middlewares.enderecos_egresso-strip.stripprefix.prefixes=/enderecos"
        - "traefik.http.middlewares.enderecos_egresso-strip.stripprefix.forceslash=true"

        - "traefik.http.routers.enderecos_egresso_https.rule=Host(`egressos.computacao.ufpa.br`) && PathPrefix(`/enderecos`)"
        - "traefik.http.routers.enderecos_egresso_https.entrypoints=https"
        - "traefik.http.routers.enderecos_egresso_https.tls=true"
        - "traefik.http.routers.enderecos_egresso_https.tls.certresolver=le"
        - "traefik.http.routers.enderecos_egresso_https.middlewares=meuegresso-headers@file,enderecos_egresso-strip@docker"
        - "traefik.http.services.enderecos_egresso_https.loadbalancer.server.port=80"

networks:
  traefik-public:
    external: true
